"""data/*.course.json 정원 → relay/size.mjs. 손으로 옮기지 않는다.

    python3 tools/build_size.py
"""
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
rows = []
for p in sorted((root / 'data').glob('*.course.json')):
    n = len(json.loads(p.read_text())['items'])
    rows.append((p.name.replace('.course.json', ''), n))

lines = [
    '/* generated by tools/build_size.py — 코스 정원. 손으로 고치지 않는다. */',
    'export const SIZE = {',
]
for i, (slug, n) in enumerate(rows):
    comma = ',' if i < len(rows) - 1 else ''
    lines.append(f"  '{slug}': {n}{comma}")
lines.append('};')
(root / 'relay' / 'size.mjs').write_text('\n'.join(lines) + '\n')
print(f'{len(rows)} courses → relay/size.mjs')
